import Head from 'next/head'
import { useState, useEffect } from 'react';
import styles from '../styles/Home.module.css'

export default function Home() {
  const [number, setNumber] = useState(0);
  const [cal, setCal] = useState('isPrime');
  const [result, setResult] = useState(false);
  const onEnterNumber = (v) => {
    let val = parseInt(v,10);
    if (isNaN(val)) {
      setNumber(0);
    } else {
      val = val >= 0 ? val : 1;
      setNumber(val);
    }
  }

  const isPrime = (num) => {
    if (num === 2) {
      return true;
    } else if (num > 1) {
      for (var i = 2; i < num; i++) {
        if (num % i !== 0) {
          return true;
        } else if (num === i * i) {
          return false
        } else {
          return false;
        }
      }
    } else {
      return false;
    }
  }

  const isSquare = (n) => {
    return n > 0 && Math.sqrt(n) % 1 === 0;
  };

  const isFibonacci = (num) => {
    if (isSquare(5*(num*num)-4) || isSquare(5*(num*num)+4)) {
       return true;
    } else { 
      return false; 
    }
}

  useEffect(() => {
    if (cal==='isPrime') {
      setResult(isPrime(number));
    } else if (cal==='isFibonacci') {
      setResult(isFibonacci(number));
    }
  }, [cal, number]);
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.colume1}>
          <input type="text" value={number} onChange={value => onEnterNumber(value.target.value)}/>
        </div>
        <div className={styles.colume2}>
        <select value={cal} onChange={value => setCal(value.target.value)}>
          <option value="isPrime">isPrime</option>
          <option value="isFibonacci">isFibonacci</option>
        </select>
        </div>
        <div className={styles.colume3}>
          {result.toString()}
        </div>
      </main>
    </div>
  )
}
